/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;

import Controlador.CtrlCategorias;
import Controlador.CtrlProductos;
import Dominio.Categoria;
import Dominio.Producto;
import Dominio.Proveedor;
import Dominio.Usuario;
import Persistencia.ProductosDAO;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author PC OSCAR
 */
public class frmMenu extends javax.swing.JFrame {

    private Long idProductoSeleccionado = 0L;
    private Usuario gerente;
    
    /**
     * Creates new form ClientesForm
     */
    public frmMenu(Usuario gerente) {
        initComponents();
        Image img = new ImageIcon(getClass().getResource("/imagenes/logo tatiaxca.png")).getImage();
        //escala imagen
        Image newimg = img.getScaledInstance(84, 79, java.awt.Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(newimg);
        //asigna a componenente JLabel
        lblLogo.setIcon(imageIcon);
        setTitle("Administrador Productos");
        this.gerente = gerente;
        //this.initTablaClientes();
        //this.llenarTabla();
    }
    
    
    
    
    
    
    
    
    
   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        panMenu = new javax.swing.JPanel();
        panBusqueda = new javax.swing.JPanel();
        btnFrmCategorias = new javax.swing.JButton();
        btnAdmonCat = new javax.swing.JButton();
        btnAdmonPro = new javax.swing.JButton();
        lblCategorias1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú principal");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        pnlHeader.setBackground(new java.awt.Color(222, 202, 184));

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(18, 93, 54));
        jLabel4.setText("Café Tatiaxca");

        panMenu.setBackground(new java.awt.Color(255, 255, 255));
        panMenu.setMaximumSize(new java.awt.Dimension(852, 405));
        panMenu.setMinimumSize(new java.awt.Dimension(852, 405));
        panMenu.setPreferredSize(new java.awt.Dimension(1084, 634));

        panBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        panBusqueda.setMaximumSize(new java.awt.Dimension(220, 300));
        panBusqueda.setMinimumSize(new java.awt.Dimension(220, 300));

        btnFrmCategorias.setBackground(new java.awt.Color(193, 232, 213));
        btnFrmCategorias.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFrmCategorias.setForeground(new java.awt.Color(51, 51, 51));
        btnFrmCategorias.setText("Registrar Venta");
        btnFrmCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrmCategoriasActionPerformed(evt);
            }
        });

        btnAdmonCat.setBackground(new java.awt.Color(193, 232, 213));
        btnAdmonCat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdmonCat.setForeground(new java.awt.Color(51, 51, 51));
        btnAdmonCat.setText("Administrar Categorías");
        btnAdmonCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmonCatActionPerformed(evt);
            }
        });

        btnAdmonPro.setBackground(new java.awt.Color(193, 232, 213));
        btnAdmonPro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdmonPro.setForeground(new java.awt.Color(51, 51, 51));
        btnAdmonPro.setText("Administrar Productos");
        btnAdmonPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmonProActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panBusquedaLayout = new javax.swing.GroupLayout(panBusqueda);
        panBusqueda.setLayout(panBusquedaLayout);
        panBusquedaLayout.setHorizontalGroup(
            panBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBusquedaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnFrmCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(btnAdmonCat, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(btnAdmonPro, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panBusquedaLayout.setVerticalGroup(
            panBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBusquedaLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(panBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFrmCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdmonCat, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdmonPro, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCategorias1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 30)); // NOI18N
        lblCategorias1.setForeground(new java.awt.Color(91, 91, 91));
        lblCategorias1.setText("Menu Principal");

        javax.swing.GroupLayout panMenuLayout = new javax.swing.GroupLayout(panMenu);
        panMenu.setLayout(panMenuLayout);
        panMenuLayout.setHorizontalGroup(
            panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenuLayout.createSequentialGroup()
                .addGroup(panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panMenuLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lblCategorias1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panMenuLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(panBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        panMenuLayout.setVerticalGroup(
            panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblCategorias1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(panBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addComponent(panMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 1234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFrmCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrmCategoriasActionPerformed
        // TODO add your handling code here:
        new frmCategorias().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFrmCategoriasActionPerformed

    private void btnAdmonProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmonProActionPerformed
        // TODO add your handling code here:
        new frmAdministrarProductos(gerente).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdmonProActionPerformed

    private void btnAdmonCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmonCatActionPerformed
        // TODO add your handling code here:
        new frmAdministrarCategorias(gerente).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdmonCatActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmonCat;
    private javax.swing.JButton btnAdmonPro;
    private javax.swing.JButton btnFrmCategorias;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCategorias1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel panBusqueda;
    private javax.swing.JPanel panMenu;
    private javax.swing.JPanel pnlHeader;
    // End of variables declaration//GEN-END:variables
}
