/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package guis;

import Dominio.Producto;
import Dominio.ProductoCarrito;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernando
 */
public class PanelBotonProducto extends javax.swing.JPanel {

    private frmProductos frmProductos;
    private List<Producto> productosFila;
    
    /**
     * Creates new form PanelBotonCategoria
     */
    public PanelBotonProducto(frmProductos frmProductos, List<Producto> productosFila) {
        initComponents();
        this.setVisible(true);
        this.frmProductos = frmProductos;
        this.productosFila = productosFila;
        this.btnProducto1.setVisible(false);
        this.btnProducto2.setVisible(false);
        this.btnProducto3.setVisible(false);
        this.btnProducto4.setVisible(false);
        this.btnProducto5.setVisible(false);
        this.btnProducto6.setVisible(false);
        List<JButton> botones = new ArrayList<>();
        botones.add(btnProducto1);
        botones.add(btnProducto2);
        botones.add(btnProducto3);
        botones.add(btnProducto4);
        botones.add(btnProducto5);
        botones.add(btnProducto6);
        int i = 0;
        while(i < productosFila.size())
        {
            botones.get(i).setText(productosFila.get(i).getNombre());
            botones.get(i).setVisible(true);
            //botones.get(i).addActionListener(al);
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProducto2 = new javax.swing.JButton();
        btnProducto1 = new javax.swing.JButton();
        btnProducto4 = new javax.swing.JButton();
        btnProducto5 = new javax.swing.JButton();
        btnProducto6 = new javax.swing.JButton();
        btnProducto3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1166, 82));
        setPreferredSize(new java.awt.Dimension(1166, 82));

        btnProducto2.setBackground(new java.awt.Color(193, 232, 213));
        btnProducto2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 19)); // NOI18N
        btnProducto2.setForeground(new java.awt.Color(91, 91, 91));
        btnProducto2.setText("Americano");
        btnProducto2.setBorder(null);
        btnProducto2.setBorderPainted(false);
        btnProducto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto2ActionPerformed(evt);
            }
        });

        btnProducto1.setBackground(new java.awt.Color(193, 232, 213));
        btnProducto1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 19)); // NOI18N
        btnProducto1.setForeground(new java.awt.Color(91, 91, 91));
        btnProducto1.setText("Americano");
        btnProducto1.setBorder(null);
        btnProducto1.setBorderPainted(false);
        btnProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto1ActionPerformed(evt);
            }
        });

        btnProducto4.setBackground(new java.awt.Color(193, 232, 213));
        btnProducto4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 19)); // NOI18N
        btnProducto4.setForeground(new java.awt.Color(91, 91, 91));
        btnProducto4.setText("Americano");
        btnProducto4.setBorder(null);
        btnProducto4.setBorderPainted(false);
        btnProducto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto4ActionPerformed(evt);
            }
        });

        btnProducto5.setBackground(new java.awt.Color(193, 232, 213));
        btnProducto5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 19)); // NOI18N
        btnProducto5.setForeground(new java.awt.Color(91, 91, 91));
        btnProducto5.setText("Americano");
        btnProducto5.setBorder(null);
        btnProducto5.setBorderPainted(false);
        btnProducto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto5ActionPerformed(evt);
            }
        });

        btnProducto6.setBackground(new java.awt.Color(193, 232, 213));
        btnProducto6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 19)); // NOI18N
        btnProducto6.setForeground(new java.awt.Color(91, 91, 91));
        btnProducto6.setText("Americano");
        btnProducto6.setBorder(null);
        btnProducto6.setBorderPainted(false);
        btnProducto6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto6ActionPerformed(evt);
            }
        });

        btnProducto3.setBackground(new java.awt.Color(193, 232, 213));
        btnProducto3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 19)); // NOI18N
        btnProducto3.setForeground(new java.awt.Color(91, 91, 91));
        btnProducto3.setText("Americano");
        btnProducto3.setBorder(null);
        btnProducto3.setBorderPainted(false);
        btnProducto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProducto4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProducto5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProducto6, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProducto4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProducto5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProducto6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void continuar(int i)
    {
        i--;
        frmProductos.productoCarrito.setNombre(productosFila.get(i).getNombre());
        Long categoria = productosFila.get(i).getIdCategoria();
        int categoriaInt = categoria.intValue();
        switch(categoriaInt)
        {
            case 4:
            {
                new frmCafeBolsaTipo(frmProductos.productosCarrito, frmProductos.productoCarrito, frmProductos).setVisible(true);
                break;
            }
            case 2:
            {
                new frmSabores(frmProductos.productosCarrito, frmProductos.productoCarrito, frmProductos).setVisible(true);
                break;
            }
            case 6:
            {
                new frmLicuados(frmProductos.productosCarrito, frmProductos.productoCarrito, frmProductos).setVisible(true);
                break;
            }
            case 7:
            {
                new frmPanTostado(frmProductos.productosCarrito, frmProductos.productoCarrito, frmProductos).setVisible(true);
                break;
            }
            case 8:
            {
                new frmTe(frmProductos.productosCarrito, frmProductos.productoCarrito, frmProductos).setVisible(true);
                break;
            }
            case 9:
            {
                new frmTizana(frmProductos.productosCarrito, frmProductos.productoCarrito, frmProductos).setVisible(true);
                break;
            }
            default:
            {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
        frmProductos.dispose();
    }
    
    private void btnProducto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto2ActionPerformed
        continuar(2);
    }//GEN-LAST:event_btnProducto2ActionPerformed

    private void btnProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto1ActionPerformed
        continuar(1);
    }//GEN-LAST:event_btnProducto1ActionPerformed

    private void btnProducto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto4ActionPerformed
        continuar(4);
    }//GEN-LAST:event_btnProducto4ActionPerformed

    private void btnProducto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto5ActionPerformed
        continuar(5);
    }//GEN-LAST:event_btnProducto5ActionPerformed

    private void btnProducto6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto6ActionPerformed
        continuar(6);
    }//GEN-LAST:event_btnProducto6ActionPerformed

    private void btnProducto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto3ActionPerformed
        continuar(3);
    }//GEN-LAST:event_btnProducto3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProducto1;
    private javax.swing.JButton btnProducto2;
    private javax.swing.JButton btnProducto3;
    private javax.swing.JButton btnProducto4;
    private javax.swing.JButton btnProducto5;
    private javax.swing.JButton btnProducto6;
    // End of variables declaration//GEN-END:variables
}
