/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package guis;

import Dominio.Categoria;
import Dominio.Producto;
import Dominio.ProductoCarrito;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author Fernando
 */
public class PanelBotonCategoria extends javax.swing.JPanel {

    private frmCategorias frmCategorias;
    private List<Categoria> categoriasFila;
    
    /**
     * Creates new form PanelBotonCategoria
     */
    public PanelBotonCategoria(frmCategorias frmCategorias, List<Categoria> categoriasFila) {
        initComponents();
        this.setVisible(true);
        this.frmCategorias = frmCategorias;
        this.categoriasFila = categoriasFila;
        this.btnCategoria1.setVisible(false);
        this.btnCategoria2.setVisible(false);
        this.btnCategoria3.setVisible(false);
        this.btnCategoria4.setVisible(false);
        this.btnCategoria5.setVisible(false);
        this.btnCategoria6.setVisible(false);
        List<JButton> botones = new ArrayList<>();
        botones.add(btnCategoria1);
        botones.add(btnCategoria2);
        botones.add(btnCategoria3);
        botones.add(btnCategoria4);
        botones.add(btnCategoria5);
        botones.add(btnCategoria6);
        int i = 0;
        while(i < categoriasFila.size())
        {
            botones.get(i).setText(categoriasFila.get(i).getNombre());
            botones.get(i).setVisible(true);
            //botones.get(i).addActionListener(al);
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCategoria2 = new javax.swing.JButton();
        btnCategoria1 = new javax.swing.JButton();
        btnCategoria4 = new javax.swing.JButton();
        btnCategoria5 = new javax.swing.JButton();
        btnCategoria6 = new javax.swing.JButton();
        btnCategoria3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1166, 82));
        setPreferredSize(new java.awt.Dimension(1166, 82));

        btnCategoria2.setBackground(new java.awt.Color(193, 232, 213));
        btnCategoria2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 19)); // NOI18N
        btnCategoria2.setForeground(new java.awt.Color(91, 91, 91));
        btnCategoria2.setText("Categoria");
        btnCategoria2.setBorder(null);
        btnCategoria2.setBorderPainted(false);
        btnCategoria2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoria2ActionPerformed(evt);
            }
        });

        btnCategoria1.setBackground(new java.awt.Color(193, 232, 213));
        btnCategoria1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 19)); // NOI18N
        btnCategoria1.setForeground(new java.awt.Color(91, 91, 91));
        btnCategoria1.setText("Categoria");
        btnCategoria1.setBorder(null);
        btnCategoria1.setBorderPainted(false);
        btnCategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoria1ActionPerformed(evt);
            }
        });

        btnCategoria4.setBackground(new java.awt.Color(193, 232, 213));
        btnCategoria4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 19)); // NOI18N
        btnCategoria4.setForeground(new java.awt.Color(91, 91, 91));
        btnCategoria4.setText("Categoria");
        btnCategoria4.setBorder(null);
        btnCategoria4.setBorderPainted(false);
        btnCategoria4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoria4ActionPerformed(evt);
            }
        });

        btnCategoria5.setBackground(new java.awt.Color(193, 232, 213));
        btnCategoria5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 19)); // NOI18N
        btnCategoria5.setForeground(new java.awt.Color(91, 91, 91));
        btnCategoria5.setText("Categoria");
        btnCategoria5.setBorder(null);
        btnCategoria5.setBorderPainted(false);
        btnCategoria5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoria5ActionPerformed(evt);
            }
        });

        btnCategoria6.setBackground(new java.awt.Color(193, 232, 213));
        btnCategoria6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 19)); // NOI18N
        btnCategoria6.setForeground(new java.awt.Color(91, 91, 91));
        btnCategoria6.setText("Categoria");
        btnCategoria6.setBorder(null);
        btnCategoria6.setBorderPainted(false);
        btnCategoria6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoria6ActionPerformed(evt);
            }
        });

        btnCategoria3.setBackground(new java.awt.Color(193, 232, 213));
        btnCategoria3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 19)); // NOI18N
        btnCategoria3.setForeground(new java.awt.Color(91, 91, 91));
        btnCategoria3.setText("Categoria");
        btnCategoria3.setBorder(null);
        btnCategoria3.setBorderPainted(false);
        btnCategoria3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoria3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCategoria3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCategoria4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCategoria5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCategoria6, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCategoria4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCategoria5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCategoria6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCategoria3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void continuar(int i)
    {
        i--;
        frmCategorias.productoCarrito.setNombre(categoriasFila.get(i).getNombre());
        Long categoria = categoriasFila.get(i).getIdCategoria();
        new frmProductos(frmCategorias.productosCarrito, categoria).setVisible(true);
        frmCategorias.dispose();
    }
    
    private void btnCategoria2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoria2ActionPerformed
        continuar(2);
    }//GEN-LAST:event_btnCategoria2ActionPerformed

    private void btnCategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoria1ActionPerformed
        continuar(1);
    }//GEN-LAST:event_btnCategoria1ActionPerformed

    private void btnCategoria4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoria4ActionPerformed
        continuar(4);
    }//GEN-LAST:event_btnCategoria4ActionPerformed

    private void btnCategoria5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoria5ActionPerformed
        continuar(5);
    }//GEN-LAST:event_btnCategoria5ActionPerformed

    private void btnCategoria6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoria6ActionPerformed
        continuar(6);
    }//GEN-LAST:event_btnCategoria6ActionPerformed

    private void btnCategoria3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoria3ActionPerformed
        continuar(3);
    }//GEN-LAST:event_btnCategoria3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategoria1;
    private javax.swing.JButton btnCategoria2;
    private javax.swing.JButton btnCategoria3;
    private javax.swing.JButton btnCategoria4;
    private javax.swing.JButton btnCategoria5;
    private javax.swing.JButton btnCategoria6;
    // End of variables declaration//GEN-END:variables
}
